name: Build MacOS Wheels

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install glx-dev sdl2-dev
        python -m pip install --upgrade pip
        pip install setuptools wheel cython twine
    - name: Build and publish
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_UPLOAD_TOKEN }}
      run: |
        python setup.py bdist_wheel
        twine upload dist/*